version: 2.1.{build}
init:
- cmd: git config --global core.autocrlf true
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.1.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
before_build:
- ps: nuget restore
build:
  project: ActiveUp.Net.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
- path: '**\*.dll'
deploy:
- provider: NuGet
  api_key:
    secure: ubOtyPLGDRR2As2YTkLUUN8cjmV66GWheJaDWf52o133MIi4Qe3nw0pUDjBkQCA2
  artifact: /.*\.nupkg/
notifications:
- provider: Email
  to:
  - reinaldo.coelho@gmail.com
  subject: FAIL - Build MailSystem.NET - Oficial
  message: Fail process build to lib MailSystem.net(https://github.com/reinaldocoelho/MailSystem.NET).
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
